### ISSUE TITLE
Help with setting up

### ISSUE THREAD

**Issue by DylanBeijersbergen** [nalajcie/tuya-sign-hacking#4]
Hi, 

Does anyone have time to help me set it up?
I'm trying to use the ``[node-red-contrib-tuyapi-cloud](https://flows.nodered.org/node/node-red-contrib-tuyapi-cloud)'' but can't figure out how to reverse engineer the following items: Key, Secret, Secret2 and Cert Sign.
I would love to control my [LSC Lamps](https://www.action.com/nl-nl/brand/lsc-smart-connect/) in Node-Red.

tnx in advance.

**Comment by nalajcie** [comment]
They are literally written in the README :).

If You would need further help, check my cli app for getting the data from the devices: https://github.com/nalajcie/tuya-cloud-to-influxdb

(I no longer have any Tuya devices, so I won't be able to help You more)
