### ISSUE TITLE
Problem with AndroidManifest.xml

### ISSUE THREAD

**Issue by mauriziobortolin** [nalajcie/tuya-sign-hacking#6]
If i try to decompiling the apk of TuyaSmart App v3.8.0, the AndroidManifest.xml file is binary file, not text file.
How to set debuggable mode in this file?

**Comment by nalajcie** [comment]
This is not related to this repo, I believe this is the basic usage of `apktool`. If You would still problems, please ask this question on some generic forum regarding android apps reverse engineering.
